// Vue/src/components/UserItem.vue
<script setup>
import { computed } from "vue"

const props = defineProps({
  avatar: {
    type: Boolean,
    default: true
  },
  avatarUrl: String,
  border: {
    type: Boolean,
    default: true
  },
  color: String,
  description: String,
  disabled: Boolean,
  loading: Boolean,
  width: {
    type: Number,
    default: 275
  },
  onClick: Function,
  online: Boolean,
  onlyAvatar: Boolean,
  reverse: Boolean,
  squared: Boolean,
  status: Boolean,
  shadow: Boolean,
  small: Boolean,
  style: Object,
  title: String,
  verified: Boolean
})

function onClickItem(e) {
  if (props.loading) return;
  if (props.onClick) return props.onClick(e);
}

function getInitials() {
  if (props.avatarUrl) return;
  const INITIALS = "AA";
  if (!props.title) return INITIALS;
  const words = props.title.split(" ");
  if (!words) return INITIALS;
  if (words.length === 0) return INITIALS;
  const initials = words.map(word => {
    if (word[0]) return word[0].toUpperCase();
  });
  return initials.join("");
}

function getSize() {
  return props.small ? '36px' : '48px'
}

const getAvatarStyle = computed(() => ({
  maxWidth: getSize(),
  minWidth: getSize(),
  maxHeight: getSize(),
  minHeight: getSize(),
  fontSize: props.small ? '14px' : '16px',
  backgroundColor: props.color || '#ccc',
  backgroundImage: `url(${props.avatarUrl})`,
  backgroundSize: "cover",
  borderRadius: props.squared ? '' : '100px',
}))

const getUserItemStyle = computed(() => ({
  display: 'flex',
  alignItems: 'center',
  padding: props.onlyAvatar ? '' : '12px 14px',
  border: props.border && !props.onlyAvatar ? '1px solid #ccc' : '',
  borderRadius: props.squared ? '' : '8px',
  fontSize: props.small ? '14px' : '17px',
  flexDirection: props.reverse ? 'row-reverse' : 'row',
  boxShadow: props.shadow && props.border ? '-1px 0px 16px 0px rgba(0,0,0,0.05)' : '',
  width: `${props.onlyAvatar ? 'fit-content' : props.width + 'px'}`,
  maxWidth: '100%',
  ...props.style
}));

const getStatusStyle = computed(() => ({
  width: '14px',
  height: '14px',
  backgroundColor: props.online ? 'limegreen' : '#ccc',
  borderRadius: '14px',
  border: '2px solid white',
  position: 'absolute',
  bottom: props.squared ? '-6px' : 0,
  right: props.squared ? '-6px' : 0
}));

const getTitleStyle = computed(() => ({
  textAlign: props.reverse ? 'right' : 'left',
  flexDirection: props.reverse ? 'row-reverse' : 'row',
  width: 'calc(80%)'
}))
</script>

<template>
  <div :class="['useritem', disabled ? 'useritem--disabled' : '']" @click="onClickItem" :style="getUserItemStyle">
    <div v-if="avatar" style="position: relative;">
      <div class="useritem--avatar" :style="getAvatarStyle">
        {{ getInitials() }}
      </div>
      <div v-if="status" :style="getStatusStyle"></div>
    </div>
    <div v-if="!onlyAvatar" :style="getTitleStyle">
      <div v-if="title" class="useritem--title truncate" style="font-weight: 700;">
        {{ title }}
      </div>
      <div v-if="description" class="useritem--description truncate">
        {{ description }}
      </div>
    </div>
  </div>
</template>

// React/src/components/UserItem.tsx
"use client";
import "./style.scss";

// export type UserItemProps = {
//   avatar?: boolean,
//   avatarUrl?: string,
//   border?: boolean,
//   color?: string;
//   children?: React.ReactNode,
//   description?: string;
//   disabled?: boolean;
//   onClick?: (event: MouseEvent) => void;
//   loading?: boolean;
//   width?: number;
//   online?: boolean;
//   onlyAvatar?: boolean;
//   reverse?: boolean;
//   squared?: boolean;
//   status?: boolean;
//   shadow?: boolean;
//   style?: React.CSSProperties;
//   title?: string;
// };

export default function UserItem({
  avatar = true,
  avatarUrl,
  border = true,
  children,
  color,
  description,
  disabled,
  loading,
  width = 275,
  onClick,
  online,
  onlyAvatar,
  reverse,
  squared,
  status,
  shadow,
  small,
  style,
  title
}: any) {
  const onClickItem = (e: any) => {
    if (loading) return;
    if (onClick) return onClick(e);
  };

  const getInitials = () => {
    if (avatarUrl) return;
    const INITIALS = "AA"
    if (!title) return INITIALS;
    const words = title.split(" ");
    if (!words) return INITIALS;
    if (words.length === 0) return INITIALS;
    const initials = words.map((word) => {
      if (word[0]) return word[0].toUpperCase()
    });
    return initials.join("");
  };

  if (loading) return <div className="useritem useritem--loading" style={{
    display: 'flex',
    alignItems: 'center',
    border: border ? '1px solid #ccc' : '',
    borderRadius: squared ? '' : '8px',
    flexDirection: reverse ? 'row-reverse' : 'row',
    boxShadow: shadow && border ? '-1px 0px 16px 0px rgba(0,0,0,0.05)' : '',
    ...style
  }}>
    <div className="useritem--loading--avatar" style={{
      borderRadius: squared ? '' : '100px',
    }}></div>
    <div style={{
      display: 'grid',
      gap: '8px'
    }}>
      <div className="useritem--loading--title" />
      <div className="useritem--loading--description" />
    </div>
  </div>

  return <div className={`useritem ${disabled ? 'useritem--disabled' : ''}`} style={{
    display: 'flex',
    alignItems: 'center',
    border: border ? '1px solid #ccc' : '',
    borderRadius: squared ? '' : '8px',
    fontSize: small ? '14px' : '16px',
    flexDirection: reverse ? 'row-reverse' : 'row',
    boxShadow: shadow && border ? '-1px 0px 16px 0px rgba(0,0,0,0.05)' : '',
    width: `${width}px`,
    maxWidth: '100%',
    ...style
  }} onClick={onClickItem}>
    {avatar && <div style={{ position: 'relative' }}>
      <div className="useritem--avatar" style={{
        maxWidth: small ? 36 : 48,
        minWidth: small ? 36 : 48,
        maxHeight: small ? 36 : 48,
        minHeight: small ? 36 : 48,
        fontSize: small ? '14px' : '16px',
        backgroundColor: color || '#ccc',
        backgroundImage: `url(${avatarUrl})`,
        backgroundSize: "cover",
        borderRadius: squared ? '' : '100px',
      }}>
        {getInitials()}
      </div>
      {status && <div style={{
        width: 14,
        height: 14,
        backgroundColor: online ? 'limegreen' : '#ccc',
        borderRadius: 14,
        border: '2px solid white',
        position: 'absolute',
        bottom: squared ? '-6px' : 0,
        right: squared ? '-6px' : 0
      }} />}
    </div>}
    {!onlyAvatar && <div style={{
      textAlign: reverse ? 'right' : 'left',
      flexDirection: reverse ? 'row-reverse' : 'row',
      width: 'calc(80%)'
    }}>
      {title && <div className="useritem--title truncate">{title}</div>}
      {description && <div className="useritem--description truncate">{description}</div>}
    </div>
    }
  </div >
}
